[project]
name = "vj"
version = "0.0.0"
requires-python = ">=3.14"
dependencies = [
  "colorlog",
  "ffmpeg-normalize",
  "pyperclip",
  "yt-dlp",
]

[dependency-groups]
dev = [
  "pytest>=8",
]

[tool.pyright]
typeCheckingMode = "strict"
venvPath = "."
venv = ".venv"
extraPaths = ["scripts"]

[tool.uv]
package = false
