name: Dependabot auto-merge
on: pull_request

permissions: {}

jobs:
  dependabot:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    concurrency:
      group: dependabot-auto-merge-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    permissions:
      contents: write # PRのマージに必要
      pull-requests: write # PRの承認に必要
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable auto-merge
        run: gh pr merge --auto --squash --delete-branch "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
